import test from 'node:test';
import assert from 'node:assert/strict';
import {sampleSla} from '../src/fixture.mjs';
import {createPacket,createReturn,validatePacket,validateReturn,analyzeReturn,applyReturn,inspectSla} from '../src/core.mjs';
const clone=value=>structuredClone(value);
async function setup(){const packet=await createPacket(sampleSla(),['headline'],'original.sla');const corrections=await createReturn(packet,{headline:['Community ','studio']});return{packet,corrections};}
async function duringDigest(index,mutation,work){const original=crypto.subtle.digest;let count=0;crypto.subtle.digest=async function(...args){count++;if(count===index)mutation();await Promise.resolve();return original.apply(this,args);};try{const result=await work();assert(count>=index,'Requested digest was reached');return result;}finally{crypto.subtle.digest=original;}}
test('validatePacket returns a detached snapshot when the caller changes its packet during digest',async()=>{const {packet}=await setup();const original=clone(packet);const validated=await duringDigest(1,()=>{packet.frames[0].runs[0].text='Changed while pending';packet.source.name='changed.sla';},()=>validatePacket(packet));assert.deepEqual(validated,original);await validatePacket(validated);validated.frames[0].runs[0].text='Only returned object';assert.equal(packet.frames[0].runs[0].text,'Changed while pending');});
test('createReturn snapshots edit arrays before awaiting packet validation',async()=>{const{packet}=await setup();const values=['Community ','studio'],edits={headline:values};const pending=createReturn(packet,edits);values[0]='Forbidden\nline';packet.frames[0].runs[0].text='Changed caller packet';const result=await pending;assert.deepEqual(result.returns[0].values,['Community ','studio']);await validateReturn(result);result.returns[0].values[0]='Detached';assert.equal(values[0],'Forbidden\nline');});
test('validateReturn returns the same detached data it validated across its nested digest',async()=>{const{corrections}=await setup();const original=clone(corrections);const checked=await duringDigest(1,()=>{corrections.returns[0].values[0]='Forbidden\nline';corrections.packet.frames[0].runs[0].text='Changed';},()=>validateReturn(corrections));assert.deepEqual(checked,original);await validateReturn(checked);});
test('analyzeReturn captures current SLA bytes and both packet inputs before awaiting',async()=>{const{packet,corrections}=await setup();const bytes=new TextEncoder().encode(sampleSla(true));const pending=analyzeReturn(bytes,corrections,packet);bytes.fill(0);corrections.returns[0].values[0]='Forbidden\nline';packet.source.name='Changed';const analysis=await pending;assert.equal(analysis.frames[0].status,'ready');assert.deepEqual(analysis.frames[0].values,['Community ','studio']);assert.equal(analysis.doc.raw,sampleSla(true));});
test('applyReturn uses captured corrections and decisions even when caller inputs mutate at the current-file digest',async()=>{const{packet,corrections}=await setup();const bytes=new TextEncoder().encode(sampleSla(true));const approvedNames=['headline'],excludeNames=[],options={originalPacket:packet,approvedNames,excludeNames};const result=await duringDigest(3,()=>{corrections.returns[0].values[0]='Forbidden\nline';corrections.packet.frames[0].runs[0].text='Changed';packet.frames[0].runs[0].text='Changed';approvedNames.length=0;excludeNames.push('headline');bytes.fill(0);},()=>applyReturn(bytes,corrections,options));assert.equal(result.output,sampleSla(true).replace('CH="Open "','CH="Community "'));assert.deepEqual(result.corrections.returns[0].values,['Community ','studio']);assert.equal(result.receipt.frames[0].status,'applied');const headline=inspectSla(result.output).frames.find(f=>f.name==='headline');assert(headline.eligible);assert.deepEqual(headline.runs.map(r=>r.text),['Community ','studio']);});
test('pending input mutation cannot add an approval that was missing at application entry',async()=>{const{packet,corrections}=await setup();const options={originalPacket:packet,approvedNames:[]};const pending=applyReturn(sampleSla(true),corrections,options);options.approvedNames.push('headline');await assert.rejects(pending,e=>e.code==='approval');});
