import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
const out=path.resolve('test-results/browser');await fs.mkdir(out,{recursive:true});
const html=await fs.readFile('dist/index.html');
const server=http.createServer((req,res)=>{if(req.url==='/'||req.url==='/frame-return/'||req.url==='/frame-return/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html);}else{res.writeHead(404);res.end('Not found');}});
await new Promise(resolve=>server.listen(4179,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,chromiumSandbox:true});
const session=await browser.newBrowserCDPSession();const commandLine=await session.send('Browser.getBrowserCommandLine');
assert(!commandLine.arguments.some(a=>a==='--no-sandbox'||a==='--disable-setuid-sandbox'),'Browser sandbox must remain enabled');
await fs.writeFile(path.join(out,'browser-command.json'),JSON.stringify(commandLine,null,2));
const report={sandbox:true,cases:[],downloads:[],screenshots:[]}, failures=[],external=[];
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4179')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
const url='http://127.0.0.1:4179/frame-return/';
async function shot(name,target=page){const file=path.join(out,name+'.png');await target.screenshot({path:file,fullPage:true});report.screenshots.push(name+'.png');}
async function check(name,fn){await fn();report.cases.push(name);console.log('PASS',name);}
async function saveDownload(selector,filename,target=page){const promised=target.waitForEvent('download');await target.locator(selector).click();const download=await promised;await download.saveAs(filename);assert.equal(await download.failure(),null);report.downloads.push(path.relative(process.cwd(),filename));return filename;}
async function openSource(file,names=['headline'],target=page){await target.goto(url);await target.locator('#language').selectOption('en');await target.locator('#source-input').setInputFiles(file);for(const name of names)await target.getByRole('checkbox',{name:`Assign ${name}`,exact:true}).check();}
async function packetToReview(file,names,label,target=page){await openSource(file,names,target);return saveDownload('#create-packet',path.join(out,label+'-review.json'),target);}
async function returnsToCurrent(current,label,target=page){const corrections=await saveDownload('#save-return',path.join(out,label+'-corrections.json'),target);await target.locator('#current-input').setInputFiles(current);await target.locator('#analyze').click();return corrections;}
async function finish(label,target=page){await target.locator('#apply-return').click();return saveDownload('#download-sla',path.join(out,label+'.sla'),target);}
try{
 await check('Keyboard entry and Japanese empty state',async()=>{await page.goto(url);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#workspace').evaluate(el=>el===document.activeElement),true);await shot('01-ja-empty');});
 await check('Explicit selection and packet download',async()=>{await openSource('generated/original.sla',[]);assert(await page.locator('#create-packet').isDisabled());await page.getByRole('checkbox',{name:'Assign headline',exact:true}).check();await shot('02-en-selection');const packetFile=await saveDownload('#create-packet',path.join(out,'review.json'));const packet=JSON.parse(await fs.readFile(packetFile));assert.deepEqual(packet.frames.map(f=>f.name),['headline']);assert.equal(packet.frames[0].runs[0].text,'Open ');});
 await check('Edit first mixed-style run and actual corrections download',async()=>{await page.locator('textarea[data-frame="headline"][data-run="0"]').fill('Community ');await shot('03-en-review');const file=await returnsToCurrent('generated/current.sla','short');const ret=JSON.parse(await fs.readFile(file));assert.deepEqual(ret.returns[0].values,['Community ','studio']);assert(await page.locator('#apply-return').isDisabled());});
 await check('Approve changed frame and actual revised/receipt downloads',async()=>{await page.getByRole('checkbox',{name:'Approve headline',exact:true}).check();await page.locator('#apply-return').click();await shot('04-en-applied');await saveDownload('#download-sla',path.join(out,'short.sla'));await saveDownload('#download-receipt',path.join(out,'short-receipt.json'));const output=await fs.readFile(path.join(out,'short.sla'),'utf8');const current=await fs.readFile('generated/current.sla','utf8');assert.equal(output,current.replace('CH="Open "','CH="Community "'));const receipt=JSON.parse(await fs.readFile(path.join(out,'short-receipt.json')));assert.equal(receipt.frames[0].status,'applied');});
 await check('Current import clears output and repeated return is stale',async()=>{await page.locator('#current-input').setInputFiles(path.join(out,'short.sla'));assert(await page.locator('#downloads').isHidden());await page.locator('#analyze').click();await page.locator('.status.conflict').waitFor();assert(await page.locator('#apply-return').isDisabled());assert.match(await page.locator('#return-list').innerText(),/Already applied/);});
 await check('Conflict blocks whole output until explicitly excluded',async()=>{await packetToReview('generated/original.sla',['headline','sidebar'],'conflict');await page.locator('textarea[data-frame="headline"][data-run="0"]').fill('Community ');await page.locator('textarea[data-frame="sidebar"]').fill('19:00');await returnsToCurrent('generated/current.sla','conflict');await page.getByRole('checkbox',{name:'Approve headline',exact:true}).check();assert(await page.locator('#apply-return').isDisabled());await shot('05-en-conflict');await page.getByRole('checkbox',{name:'Exclude sidebar',exact:true}).check();const file=await finish('conflict-excluded');assert.equal(await fs.readFile(file,'utf8'),(await fs.readFile('generated/current.sla','utf8')).replace('CH="Open "','CH="Community "'));});
 await check('No-op actual download is byte-identical',async()=>{await packetToReview('generated/original.sla',['headline'],'noop');await returnsToCurrent('generated/current.sla','noop');const file=await finish('noop');assert.deepEqual(await fs.readFile(file),await fs.readFile('generated/current.sla'));});
 await check('Fixed boundaries reject newline and block return packet',async()=>{await packetToReview('generated/original.sla',['headline'],'newline');await page.locator('textarea[data-frame="headline"][data-run="0"]').fill('Two\nparagraphs');await page.locator('#save-return').click();await page.locator('#notice.error').waitFor();assert(await page.locator('#review-panel').isVisible());await page.locator('#tab-apply').click();assert(await page.locator('#analyze').isDisabled());assert(await page.locator('#downloads').isHidden());});
 await check('Fresh designer imports original packet separately',async()=>{await page.goto(url);await page.locator('#language').selectOption('en');await page.locator('#tab-apply').click();await page.locator('#return-input').setInputFiles(path.join(out,'short-corrections.json'));await page.locator('#current-input').setInputFiles('generated/current.sla');assert(await page.locator('#analyze').isDisabled());await page.locator('#assignment-input').setInputFiles(path.join(out,'review.json'));await page.locator('#analyze').click();await page.getByRole('checkbox',{name:'Approve headline',exact:true}).check();await finish('separate-imports');});
 await check('Malformed imports remove previous valid output',async()=>{await fs.writeFile(path.join(out,'broken.json'),'{broken');await page.locator('#return-input').setInputFiles(path.join(out,'broken.json'));await page.locator('#notice.error').waitFor();assert(await page.locator('#downloads').isHidden());assert(await page.locator('#analyze').isDisabled());});
 await check('Source reload resets downstream dependencies and reset clears file inputs',async()=>{await page.locator('#tab-prepare').click();await page.locator('#sample-source').click();await page.locator('#tab-apply').click();assert(await page.locator('#analyze').isDisabled());assert(await page.locator('#downloads').isHidden());await page.locator('#reset').click();assert(await page.locator('#prepare-panel').isVisible());assert(await page.locator('#create-packet').isDisabled());assert.equal(await page.locator('input[type=file]').evaluateAll(items=>items.reduce((sum,i)=>sum+i.files.length,0)),0);});
 await check('Packet checksum tampering is rejected in review import',async()=>{const packet=JSON.parse(await fs.readFile(path.join(out,'review.json')));packet.frames[0].runs[0].text='Hacked ';await fs.writeFile(path.join(out,'tampered.json'),JSON.stringify(packet));await page.locator('#tab-review').click();await page.locator('#review-input').setInputFiles(path.join(out,'tampered.json'));await page.locator('#notice.error').waitFor();assert(await page.locator('#save-return').isDisabled());});
 await check('Mobile Japanese review and conflict layouts have no horizontal overflow',async()=>{const phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await packetToReview('generated/original.sla',['headline','sidebar'],'mobile',phone);await phone.locator('#language').selectOption('ja');await phone.locator('textarea[data-frame="headline"][data-run="0"]').fill('Community ');await shot('06-ja-mobile-review',phone);assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await returnsToCurrent('generated/current.sla','mobile',phone);await shot('07-ja-mobile-conflict',phone);assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await phone.close();});
 if(process.env.NATIVE_WORKDIR){
   const work=path.resolve(process.env.NATIVE_WORKDIR),manifest=JSON.parse(await fs.readFile(path.join(work,'manifest.json')));
   const contract=manifest.contract??manifest;assert.equal(contract.scribusVersion,'1.6.1');
   for(const name of ['short','long'])await check(`Native-generated fixture → actual browser ${name} download`,async()=>{
     await packetToReview(path.join(work,'baseline.sla'),['headline'],`native-${name}`);
     assert.equal(await page.locator('textarea[data-frame="headline"]').count(),2);
     await page.locator('textarea[data-frame="headline"][data-run="0"]').fill(contract.cases[name].runs[0]);
     await returnsToCurrent(path.join(work,'current.sla'),`native-${name}`);
     await page.getByRole('checkbox',{name:'Approve headline',exact:true}).check();
     await page.locator('#apply-return').click();
     await saveDownload('#download-sla',path.join(work,`returned-${name}.sla`));
     await saveDownload('#download-receipt',path.join(work,`returned-${name}-receipt.json`));
     await fs.writeFile(path.join(work,`expected-${name}.json`),JSON.stringify({frames:{headline:contract.cases[name].runs}},null,2));
     if(name==='short')await shot('08-native-return');
   });
   await check('Native sidebar 18:00 baseline conflicts with current 18:30',async()=>{await packetToReview(path.join(work,'baseline.sla'),['sidebar'],'native-stale-sidebar');await page.locator('textarea[data-frame="sidebar"]').fill('19:00');await returnsToCurrent(path.join(work,'current.sla'),'native-stale-sidebar');assert(await page.locator('#apply-return').isDisabled());assert.equal(await page.locator('.status.conflict').count(),1);});
 }
 assert.deepEqual(failures,[]);assert.deepEqual(external,[]);report.pageErrors=failures;report.externalRequests=external;report.ok=true;
} catch(error){report.ok=false;report.error=error.stack;await shot('failure').catch(()=>{});throw error;}
finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await context.tracing.stop({path:path.join(out,'trace.zip')});await browser.close();await new Promise(resolve=>server.close(resolve));}
